In [6]:
import numpy as np
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.metrics import accuracy_score, confusion_matrix

In [7]:

# Load the diabetes dataset
diabetes = load_diabetes()
X = diabetes.data
y = diabetes.target

# Split the data into training and validation sets
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)


In [8]:

# Create the model
model = Sequential()
model.add(Dense(6, activation='relu'))
model.add(Dense(3, activation='relu'))
model.add(Dense(1))

# Compile the model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

# Train the model
model.fit(X_train, y_train, epochs=500, batch_size=32, validation_data=(X_val, y_val))


TypeError: only integer scalar arrays can be converted to a scalar index

In [ ]:
y_pred = model.predict(X_val)
y_pred = np.round(y_pred).flatten()
accuracy = accuracy_score(y_val, y_pred)
print("Accuracy on validation set: {:.2f}%".format(accuracy * 100))

cm = confusion_matrix(y_val, y_pred)
print("Confusion matrix:\n", cm)

3/3 [==============================] - 0s 2ms/step
Accuracy on validation set: 0.00%
Confusion matrix:
 [[0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]]
